version: '3.8'

networks:
  angorasix-net:
    driver: bridge

services:
  # INFRA
  a6-mongo:
    image: mongo
    command: ["--replSet", "myReplicaSet"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'myReplicaSet',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    networks:
      - angorasix-net
    ports:
      - '27017:27017'

  a6-rabbitmq:
    image: rabbitmq:management
    networks:
      - angorasix-net
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./resources/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./resources/rabbitmq/definitions/:/etc/rabbitmq/definitions/
      # - ./resources/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins

  a6-axon:
    image: axoniq/axonserver
    networks:
      - angorasix-net
    ports:
      - '8024:8024'
      - '8124:8124'
    environment:
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true
      - AXONIQ_AXONSERVER_STANDALONE=true

  #CONTRIBUTORS
  contributors:
    image: "angorasix/contributors:${TAG:-latest}"
    restart: unless-stopped
    networks:
      - angorasix-net
    build:
      context: ../contributors
    environment:
      A6_CONTRIBUTORS_PORT: 8080
      A6_CONTRIBUTORS_LOGGING_LEVEL_ROOT: ${A6_INFRA_A6_CONTRIBUTORS_LOGGING_LEVEL_ROOT:-INFO}
      A6_CONTRIBUTORS_LOGGING_LEVEL_AUTHORIZATION: ${A6_INFRA_A6_CONTRIBUTORS_LOGGING_LEVEL_AUTHORIZATION:-INFO}
      A6_CONTRIBUTORS_LOGGING_LEVEL_CLIENT: ${A6_INFRA_A6_CONTRIBUTORS_LOGGING_LEVEL_CLIENT:-INFO}
      A6_CONTRIBUTORS_MONGO_DB_URI: ${A6_INFRA_A6_MONGO_URL}
      A6_CONTRIBUTORS_MONGO_DB_NAME: 'a6ContributorsLocal'
      A6_CONTRIBUTORS_MONGO_DB_PARAMS: '?retryWrites=true&w=majority'
      A6_CONTRIBUTORS_MONGO_DB_SSL_ENABLED: ${A6_INFRA_A6_MONGO_SSL_ENABLED:-false}
      # Server setup
      A6_CONTRIBUTORS_SERVER_PROXY_STRATEGY: ${A6_INFRA_A6_CONTRIBUTORS_SERVER_PROXY_STRATEGY:-FRAMEWORK}
      A6_CONTRIBUTORS_SERVER_PROXY_REDIRECT: ${A6_INFRA_A6_CONTRIBUTORS_SERVER_PROXY_REDIRECT:-false}
      # AS setup
      A6_CONTRIBUTORS_AUTHZ_CLIENT_SECRET: ${A6_INFRA_A6_CONTRIBUTORS_AUTHZ_CLIENT_SECRET}
      A6_CONTRIBUTORS_AN_AUTHZ_REDIRECT_URI: ${A6_INFRA_A6_CONTRIBUTORS_AN_AUTHZ_REDIRECT_URI}
      A6_CONTRIBUTORS_A6_AUTHZ_REDIRECT_URI: ${A6_INFRA_A6_CONTRIBUTORS_A6_AUTHZ_REDIRECT_URI}
      # Google Login
      A6_CONTRIBUTORS_CLIENT_GOOGLE_CLIENT_ID: ${A6_INFRA_A6_CONTRIBUTORS_CLIENT_GOOGLE_CLIENT_ID}
      A6_CONTRIBUTORS_CLIENT_GOOGLE_CLIENT_SECRET: ${A6_INFRA_A6_CONTRIBUTORS_CLIENT_GOOGLE_CLIENT_SECRET}
    ports:
      - '10100:8080'

  # BACKEND SERVICES
  projects.core:
    image: "angorasix/projects.core:${TAG:-latest}"
    restart: unless-stopped
    networks:
      - angorasix-net
    build:
      context: ../projects/core
    environment:
      A6_PROJECTS_CORE_PORT: 8080
      A6_PROJECTS_CORE_MONGO_DB_URI: ${A6_INFRA_A6_MONGO_URL}
      A6_PROJECTS_CORE_MONGO_DB_NAME: a6ProjectsCoreLocal
      A6_PROJECTS_CORE_MONGO_DB_PARAMS: '?retryWrites=true&w=majority'
      A6_PROJECTS_CORE_OAUTH_SECURITY_ISSUER_URI: ${A6_INFRA_A6_PROJECTS_CORE_OAUTH_SECURITY_ISSUER_URI:-http://contributors:8080}
    ports:
      - '10200:8080'

  projects.presentations:
    image: "angorasix/projects.presentations:${TAG:-latest}"
    restart: unless-stopped
    networks:
      - angorasix-net
    build:
      context: ../projects/presentations
    environment:
      A6_PROJECTS_PRESENTATIONS_PORT: 8080
      A6_PROJECTS_PRESENTATIONS_MONGO_DB_URI: ${A6_INFRA_A6_MONGO_URL}
      A6_PROJECTS_PRESENTATIONS_MONGO_DB_NAME: a6ProjectsPresentationsLocal
      A6_PROJECTS_PRESENTATIONS_MONGO_DB_PARAMS: '?retryWrites=true&w=majority'
      A6_PROJECTS_PRESENTATIONS_OAUTH_SECURITY_ISSUER_URI: ${A6_INFRA_A6_PROJECTS_PRESENTATIONS_OAUTH_SECURITY_ISSUER_URI:-http://contributors:8080}
    ports:
      - '10201:8080'

  media:
    image: "angorasix/media:${TAG:-latest}"
    restart: unless-stopped
    networks:
      - angorasix-net
    build:
      context: ../media
    volumes:
      - ./resources/media:/root/config
      - ./config/media/angorasix-a6.media.local.json:/config/gcpStorageCredentials.json
    environment:
      A6_MEDIA_SVC_HOST: ${A6_INFRA_A6_MEDIA_SVC_HOST}
      A6_MEDIA_SVC_PORT: ${A6_INFRA_A6_MEDIA_SVC_PORT}
      A6_MEDIA_SVC_PROTOCOL: ${A6_INFRA_A6_MEDIA_SVC_PROTOCOL}
      A6_MEDIA_SVC_STRATEGY: ${A6_INFRA_A6_MEDIA_SVC_STRATEGY}
      A6_MEDIA_SVC_BUCKET_NAME: ${A6_INFRA_A6_MEDIA_SVC_BUCKET_NAME:-nullBucketName}
      A6_MEDIA_SVC_PROJECT_ID: ${A6_INFRA_A6_MEDIA_SVC_PROJECT_ID:-nullProjectId}
      A6_MEDIA_SVC_STORAGE_API_HOST: ${A6_INFRA_A6_MEDIA_STORAGE_API_HOST:-nullStorageApiHost}
      GOOGLE_APPLICATION_CREDENTIALS: ${A6_INFRA_A6_MEDIA_GOOGLE_APPLICATION_CREDENTIALS:-nullGoogleApplicationCredentials}
      # A6_MEDIA_SVC_THUMBNAIL_MAX_WIDTH:
      # A6_MEDIA_SVC_THUMBNAIL_MAX_HEIGHT:
      # A6_MEDIA_SVC_THUMBNAIL_MAX_SIZE:
      # A6_MEDIA_SVC_THUMBNAIL_JPG_QUALITY:
      # A6_MEDIA_SVC_THUMBNAIL_PNG_COMPRESSION:
    ports:
      - "10001:80"

  clubs:
    image: "angorasix/clubs:${TAG:-latest}"
    restart: unless-stopped
    networks:
      - angorasix-net
    build:
      context: ../clubs
    environment:
      A6_CLUBS_PORT: 8080
      A6_CLUBS_MONGO_DB_URI: ${A6_INFRA_A6_MONGO_URL}
      A6_CLUBS_MONGO_DB_NAME: 'a6ClubsLocal'
      A6_CLUBS_MONGO_DB_PARAMS: '?retryWrites=true&w=majority'
      A6_CLUBS_OAUTH_SECURITY_ISSUER_URI: ${A6_INFRA_A6_CLUBS_OAUTH_SECURITY_ISSUER_URI:-http://contributors:8080}
    ports:
      - '10900:8080'
  
  projects.management.core:
    image: "angorasix/projects.management.core:${TAG-latest}"
    restart: unless-stopped
    networks:
      - angorasix-net
    build:
      context: ../projects/mgmt/core
    environment:
      A6_PROJECTS_MGMT_CORE_PORT: 8080
      A6_PROJECTS_MGMT_CORE_MONGO_DB_URI: ${A6_INFRA_A6_MONGO_URL}
      A6_PROJECTS_MGMT_CORE_MONGO_DB_NAME: a6ProjectsManagementCoreLocal
      A6_PROJECTS_MGMT_CORE_MONGO_DB_PARAMS: '?retryWrites=true&w=majority'
      A6_PROJECTS_MGMT_CORE_OAUTH_SECURITY_ISSUER_URI: ${A6_INFRA_A6_PROJECTS_MGMT_CORE_OAUTH_SECURITY_ISSUER_URI:-http://contributors:8080}
    ports:
      - '10300:8080'

  events:
    image: "angorasix/events:${TAG-latest}"
    restart: unless-stopped
    networks:
      - angorasix-net
    build:
      context: ../events
    environment:
      A6_EVENTS_PORT: 8080
      A6_EVENTS_RABBITMQ_HOST: ${A6_INFRA_A6_RABBITMQ_HOST}
      A6_EVENTS_RABBITMQ_PORT: ${A6_INFRA_A6_RABBITMQ_PORT:-5672}
      A6_EVENTS_RABBITMQ_VHOST: ${A6_INFRA_A6_RABBITMQ_VHOST:-/}
      A6_EVENTS_RABBITMQ_USER: ${A6_INFRA_A6_RABBITMQ_USER:-guest}
      A6_EVENTS_RABBITMQ_PASSWORD: ${A6_INFRA_A6_RABBITMQ_PASSWORD:-guest}
      A6_EVENTS_OAUTH_SECURITY_ISSUER_URI: ${A6_INFRA_A6_EVENTS_OAUTH_SECURITY_ISSUER_URI:-http://contributors:8080}
    ports:
      - '10101:8080'

  notifications:
    image: "angorasix/notifications:${TAG-latest}"
    restart: unless-stopped
    networks:
      - angorasix-net
    build:
      context: ../notifications
    environment:
      A6_NOTIFICATIONS_PORT: 8080
      A6_NOTIFICATIONS_RABBITMQ_HOST: ${A6_INFRA_A6_RABBITMQ_HOST}
      A6_NOTIFICATIONS_RABBITMQ_PORT: ${A6_INFRA_A6_RABBITMQ_PORT:-5672}
      A6_NOTIFICATIONS_RABBITMQ_VHOST: ${A6_INFRA_A6_RABBITMQ_VHOST:-/}
      A6_NOTIFICATIONS_RABBITMQ_USER: ${A6_INFRA_A6_RABBITMQ_USER:-guest}
      A6_NOTIFICATIONS_RABBITMQ_PASSWORD: ${A6_INFRA_A6_RABBITMQ_PASSWORD:-guest}
      A6_NOTIFICATIONS_MONGO_DB_URI: ${A6_INFRA_A6_MONGO_URL}
      A6_NOTIFICATIONS_MONGO_DB_NAME: a6Notifications
      A6_NOTIFICATIONS_MONGO_DB_PARAMS: '?retryWrites=true&w=majority'
      A6_NOTIFICATIONS_OAUTH_SECURITY_ISSUER_URI: ${A6_INFRA_A6_NOTIFICATIONS_OAUTH_SECURITY_ISSUER_URI:-http://contributors:8080}
    ports:
      - '10102:8080'

  projects.management.tasks:
    image: "angorasix/projects.management.tasks:${TAG-latest}"
    restart: unless-stopped
    networks:
      - angorasix-net
    build:
      context: ../projects/mgmt/tasks
    environment:
      A6_PROJECTS_MGMT_CORE_PORT: 8080
      A6_PROJECTS_MGMT_CORE_MONGO_DB_URI: ${A6_INFRA_A6_MONGO_URL}
      A6_PROJECTS_MGMT_CORE_MONGO_DB_NAME: a6ProjectsManagementTasksLocal
      A6_PROJECTS_MGMT_CORE_MONGO_DB_PARAMS: '?retryWrites=true&w=majority'
      A6_PROJECTS_MGMT_CORE_OAUTH_SECURITY_ISSUER_URI: ${A6_INFRA_A6_PROJECTS_MGMT_TASKS_OAUTH_SECURITY_ISSUER_URI:-http://contributors:8080}
    ports:
      - '10301:8080'

  # INTEGRATIONS

  integrations.iframe:
    image: "angorasix/integrations.iframe:${TAG-latest}"
    restart: unless-stopped
    build:
      context: ../integrations/iframe
    environment:
      A6_INTEGRATIONS_IFRAME_SVC_PORT: 8080
    ports:
      - '10002:8080'

  # FRONT
  front.aindanow:
    image: "angorasix/front.aindanow:${TAG-latest}"
    restart: unless-stopped
    networks:
      - angorasix-net
    build:
      context: ../front/AindaNow
    environment:
      NEXTAUTH_URL:  ${A6_INFRA_AN_CANONICAL_URL_AINDANOW}
      NEXTAUTH_URL_INTERNAL: ${A6_INFRA_AN_NEXTAUTH_URL_INTERNAL:-http://front.aindanow:80}
      AN_APP_API_SERVER_BASE_URL: ${A6_INFRA_AN_APP_API_SERVER_BASE_URL}
      AN_APP_API_BROWSER_BASE_URL: ${A6_INFRA_AN_APP_API_BROWSER_BASE_URL}
      AN_APP_API_EVENTSOURCE_LOCALHOST: ${A6_INFRA_AN_APP_API_EVENTSOURCE_LOCALHOST}
      AN_APP_AN_FRONT_PUBLIC_MEDIA_SERVER_BASE_URL: ${A6_INFRA_AN_APP_AN_FRONT_PUBLIC_MEDIA_SERVER_BASE_URL}
      AN_APP_AUTH_COOKIE: ${A6_INFRA_AN_APP_AUTH_COOKIE}
      AN_APP_THIRDPARTIES_YOUTUBE_APIKEY: ${A6_INFRA_AN_APP_THIRDPARTIES_YOUTUBE_APIKEY}
      AN_APP_OAUTH_PROVIDER_ISSUER: ${A6_INFRA_AN_APP_OAUTH_PROVIDER_ISSUER}
      AN_APP_OAUTH_PROVIDER_TOKEN_ENDPOINT: ${A6_INFRA_AN_APP_OAUTH_PROVIDER_TOKEN_ENDPOINT:-http://contributors:8080/not-overriden/token}
      AN_APP_OAUTH_PROVIDER_AUTHORIZATION_ENDPOINT: ${A6_INFRA_AN_APP_OAUTH_PROVIDER_AUTHORIZATION_ENDPOINT:-http://contributors:8080/not-overriden/authorize}
      AN_APP_OAUTH_PROVIDER_JWKS_ENDPOINT: ${A6_INFRA_AN_APP_OAUTH_PROVIDER_JWKS_ENDPOINT:-http://contributors:8080/not-overriden/oauth2/jwks}
      AN_APP_OAUTH_CLIENT_ID: ${A6_INFRA_AN_APP_OAUTH_CLIENT_ID}
      AN_APP_OAUTH_CLIENT_SECRET: ${A6_INFRA_AN_APP_OAUTH_CLIENT_SECRET}
      AN_APP_OAUTH_REDIRECT_URI: ${A6_INFRA_AN_APP_OAUTH_REDIRECT_URI}
      AN_APP_OAUTH_JWT_SECRET: ${A6_INFRA_AN_APP_OAUTH_JWT_SECRET}
      AN_APP_MAIN_SECRET: ${A6_INFRA_AN_APP_MAIN_SECRET}
      NODE_TLS_REJECT_UNAUTHORIZED: ${A6_INFRA_AN_NODE_TLS_REJECT_UNAUTHORIZED:-1}
      AN_APP_OAUTH_FW_DEBUG: ${A6_INFRA_AN_APP_OAUTH_FW_DEBUG:-true}
      AN_APP_THIRDPARTIES_ANGORASIX_HOST: ${A6_INFRA_AN_APP_THIRDPARTIES_ANGORASIX_HOST:-http://localhost:10700}
    ports:
      - "10701:80"

  front.angorasix:
    image: "angorasix/front.angorasix:${TAG-latest}"
    restart: unless-stopped
    networks:
      - angorasix-net
    build:
      context: ../front/AngoraSix
    environment:
      NEXTAUTH_URL:  ${A6_INFRA_A6_CANONICAL_URL_ANGORASIX}
      NEXTAUTH_URL_INTERNAL: ${A6_INFRA_A6_NEXTAUTH_URL_INTERNAL:-http://front.angorasix:80}
      A6_APP_API_SERVER_BASE_URL: ${A6_INFRA_A6_APP_API_SERVER_BASE_URL}
      A6_APP_API_BROWSER_BASE_URL: ${A6_INFRA_A6_APP_API_BROWSER_BASE_URL}
      A6_APP_API_EVENTSOURCE_LOCALHOST: ${A6_INFRA_A6_APP_API_EVENTSOURCE_LOCALHOST}
      A6_APP_AUTH_COOKIE: ${A6_INFRA_A6_APP_AUTH_COOKIE}
      A6_APP_THIRDPARTIES_YOUTUBE_APIKEY: ${A6_INFRA_A6_APP_THIRDPARTIES_YOUTUBE_APIKEY}
      A6_APP_OAUTH_PROVIDER_ISSUER: ${A6_INFRA_A6_APP_OAUTH_PROVIDER_ISSUER}
      A6_APP_OAUTH_PROVIDER_TOKEN_ENDPOINT: ${A6_INFRA_A6_APP_OAUTH_PROVIDER_TOKEN_ENDPOINT:-http://contributors:8080/not-overriden/token}
      A6_APP_OAUTH_PROVIDER_AUTHORIZATION_ENDPOINT: ${A6_INFRA_A6_APP_OAUTH_PROVIDER_AUTHORIZATION_ENDPOINT:-http://contributors:8080/not-overriden/authorize}
      A6_APP_OAUTH_PROVIDER_JWKS_ENDPOINT: ${A6_INFRA_A6_APP_OAUTH_PROVIDER_JWKS_ENDPOINT:-http://contributors:8080/not-overriden/oauth2/jwks}
      A6_APP_OAUTH_CLIENT_ID: ${A6_INFRA_A6_APP_OAUTH_CLIENT_ID}
      A6_APP_OAUTH_CLIENT_SECRET: ${A6_INFRA_A6_APP_OAUTH_CLIENT_SECRET}
      A6_APP_OAUTH_REDIRECT_URI: ${A6_INFRA_A6_APP_OAUTH_REDIRECT_URI}
      A6_APP_OAUTH_JWT_SECRET: ${A6_INFRA_A6_APP_OAUTH_JWT_SECRET}
      A6_APP_MAIN_SECRET: ${A6_INFRA_A6_APP_MAIN_SECRET}
      NODE_TLS_REJECT_UNAUTHORIZED: ${A6_INFRA_AN_NODE_TLS_REJECT_UNAUTHORIZED:-1}
      A6_APP_OAUTH_FW_DEBUG: ${A6_INFRA_A6_APP_OAUTH_FW_DEBUG:-true}
    ports:
      - "10700:80"

  # GATEWAY
  gateway:
    image: "angorasix/gateway:${TAG:-latest}"
    restart: unless-stopped
    networks:
      - angorasix-net
    volumes:
      - ./config/gateway:/config
    build:
      context: ../gateway
    environment:
      A6_GATEWAY_PORT: 8080
      A6_GATEWAY_CONTRIBUTORS_URI: ${A6_INFRA_GATEWAY_CONTRIBUTORS_URI:-http://contributors:8080}
      A6_GATEWAY_PROJECTS_CORE_URI: ${A6_INFRA_GATEWAY_PROJECTS_CORE_URI:-http://projects.core:8080}
      A6_GATEWAY_PROJECTS_PRESENTATION_URI: ${A6_INFRA_GATEWAY_PROJECTS_PRESENTATION_URI:-http://projects.presentations:8080}
      A6_GATEWAY_PROJECTS_MANAGEMENT_URI: ${A6_INFRA_GATEWAY_PROJECTS_MANAGEMENT_URI:-http://projects.management.core:8080}
      A6_GATEWAY_MEDIA_URI: ${A6_INFRA_GATEWAY_MEDIA_URI:-http://media:80}
      A6_GATEWAY_CLUBS_URI: ${A6_INFRA_GATEWAY_CLUBS_URI:-http://clubs:8080}
      A6_GATEWAY_EVENTS_URI: ${A6_INFRA_GATEWAY_EVENTS_URI:-http://events:8080}
      A6_GATEWAY_NOTIFICATIONS_URI: ${A6_INFRA_GATEWAY_NOTIFICATIONS_URI:-http://notifications:8080}
      A6_GATEWAY_OAUTH_SECURITY_ISSUER_URI: ${A6_INFRA_GATEWAY_OAUTH_SECURITY_ISSUER_URI:-http://contributors:8080}
      A6_GATEWAY_CORS_ALLOWEDORIGINS: ${A6_INFRA_A6_GATEWAY_CORS_ALLOWEDORIGINS}
      A6_GATEWAY_LOGGING_LEVEL_GATEWAY: ${A6_INFRA_A6_GATEWAY_LOGGING_LEVEL:-DEBUG}
    ports:
      - '10000:8080'
