version: '3.8'

services:
  # INFRA
  a6-mongo:
    image: mongo
    network_mode: host
    command: ["--replSet", "myReplicaSet"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'myReplicaSet',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

  a6-rabbitmq:
    image: rabbitmq:management
    network_mode: host
    volumes:
      - ./resources/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./resources/rabbitmq/definitions/:/etc/rabbitmq/definitions/

  #CONTRIBUTORS
  contributors:
    image: 'angorasix/contributors:${TAG:-latest}'
    restart: on-failure:3
    network_mode: host
    build:
      context: ../contributors
    environment:
      A6_CONTRIBUTORS_PORT: 10100
      A6_CONTRIBUTORS_LOGGING_LEVEL_ROOT: ${A6_INFRA_A6_CONTRIBUTORS_LOGGING_LEVEL_ROOT:-INFO}
      A6_CONTRIBUTORS_LOGGING_LEVEL_AUTHORIZATION: ${A6_INFRA_A6_CONTRIBUTORS_LOGGING_LEVEL_AUTHORIZATION:-INFO}
      A6_CONTRIBUTORS_LOGGING_LEVEL_CLIENT: ${A6_INFRA_A6_CONTRIBUTORS_LOGGING_LEVEL_CLIENT:-INFO}
      A6_CONTRIBUTORS_MONGO_DB_URI: ${A6_INFRA_A6_MONGO_URL_LOCALHOST}
      A6_CONTRIBUTORS_MONGO_DB_PARAMS: '?retryWrites=true&w=majority'
      A6_CONTRIBUTORS_MONGO_DB_SSL_ENABLED: ${A6_INFRA_A6_MONGO_SSL_ENABLED:-false}
      # Server setup
      A6_CONTRIBUTORS_SERVER_PROXY_STRATEGY: ${A6_INFRA_A6_CONTRIBUTORS_SERVER_PROXY_STRATEGY:-FRAMEWORK}
      A6_CONTRIBUTORS_SERVER_PROXY_REDIRECT: ${A6_INFRA_A6_CONTRIBUTORS_SERVER_PROXY_REDIRECT:-false}
      # AS setup
      A6_CONTRIBUTORS_AUTHZ_CLIENT_SECRET: ${A6_INFRA_A6_CONTRIBUTORS_AUTHZ_CLIENT_SECRET}
      A6_CONTRIBUTORS_AN_AUTHZ_REDIRECT_URI: ${A6_INFRA_A6_CONTRIBUTORS_AN_AUTHZ_REDIRECT_URI}
      A6_CONTRIBUTORS_A6_AUTHZ_REDIRECT_URI: ${A6_INFRA_A6_CONTRIBUTORS_A6_AUTHZ_REDIRECT_URI}
      # Google Login
      A6_CONTRIBUTORS_CLIENT_GOOGLE_CLIENT_ID: ${A6_INFRA_A6_CONTRIBUTORS_CLIENT_GOOGLE_CLIENT_ID}
      A6_CONTRIBUTORS_CLIENT_GOOGLE_CLIENT_SECRET: ${A6_INFRA_A6_CONTRIBUTORS_CLIENT_GOOGLE_CLIENT_SECRET}

  # BACKEND SERVICES
  projects.core:
    image: 'angorasix/projects.core:${TAG:-latest}'
    restart: on-failure:3
    network_mode: host
    build:
      context: ../projects/core
    environment:
      A6_PROJECTS_CORE_PORT: 10200
      A6_PROJECTS_CORE_MONGO_DB_URI: ${A6_INFRA_A6_MONGO_URL_LOCALHOST}
      A6_PROJECTS_CORE_MONGO_DB_PARAMS: '?retryWrites=true&w=majority'
      A6_PROJECTS_CORE_OAUTH_SECURITY_ISSUER_URI: http://localhost:10100

  projects.presentations:
    image: 'angorasix/projects.presentations:${TAG:-latest}'
    restart: on-failure:3
    network_mode: host
    # networks:
    #   - angorasix-net
    build:
      context: ../projects/presentations
    environment:
      A6_PROJECTS_PRESENTATIONS_PORT: 10201
      A6_PROJECTS_PRESENTATIONS_MONGO_DB_URI: ${A6_INFRA_A6_MONGO_URL_LOCALHOST}
      A6_PROJECTS_PRESENTATIONS_MONGO_DB_PARAMS: '?retryWrites=true&w=majority'
      A6_PROJECTS_PRESENTATIONS_OAUTH_SECURITY_ISSUER_URI: http://localhost:10100

  media:
    image: 'angorasix/media:${TAG:-latest}'
    restart: on-failure:3
    network_mode: host
    build:
      context: ../media
    volumes:
      - ./resources/media:/root/config
      - ./config/media/angorasix-a6.media.local.json:/config/gcpStorageCredentials.json
    environment:
      A6_MEDIA_SVC_HOST: ${A6_INFRA_A6_MEDIA_SVC_HOST}
      A6_MEDIA_SVC_PORT: ${A6_INFRA_A6_MEDIA_SVC_PORT_LOCALHOST}
      A6_MEDIA_SVC_PROTOCOL: ${A6_INFRA_A6_MEDIA_SVC_PROTOCOL}
      A6_MEDIA_SVC_STRATEGY: ${A6_INFRA_A6_MEDIA_SVC_STRATEGY}
      A6_MEDIA_SVC_BUCKET_NAME: ${A6_INFRA_A6_MEDIA_SVC_BUCKET_NAME:-nullBucketName}
      A6_MEDIA_SVC_PROJECT_ID: ${A6_INFRA_A6_MEDIA_SVC_PROJECT_ID:-nullProjectId}
      A6_MEDIA_SVC_STORAGE_API_HOST: ${A6_INFRA_A6_MEDIA_STORAGE_API_HOST:-nullStorageApiHost}
      GOOGLE_APPLICATION_CREDENTIALS: ${A6_INFRA_A6_MEDIA_GOOGLE_APPLICATION_CREDENTIALS:-nullGoogleApplicationCredentials}
      # A6_MEDIA_SVC_THUMBNAIL_MAX_WIDTH:
      # A6_MEDIA_SVC_THUMBNAIL_MAX_HEIGHT:
      # A6_MEDIA_SVC_THUMBNAIL_MAX_SIZE:
      # A6_MEDIA_SVC_THUMBNAIL_JPG_QUALITY:
      # A6_MEDIA_SVC_THUMBNAIL_PNG_COMPRESSION:

  clubs:
    image: 'angorasix/clubs:${TAG:-latest}'
    restart: on-failure:3
    network_mode: host
    build:
      context: ../clubs
    environment:
      A6_CLUBS_PORT: 10900
      A6_CLUBS_MONGO_DB_URI: ${A6_INFRA_A6_MONGO_URL_LOCALHOST}
      A6_CLUBS_MONGO_DB_PARAMS: '?retryWrites=true&w=majority'
      A6_CLUBS_OAUTH_SECURITY_ISSUER_URI: http://localhost:10100

  projects.management.core:
    image: 'angorasix/projects.management.core:${TAG-latest}'
    restart: on-failure:3
    network_mode: host
    build:
      context: ../projects/mgmt/core
    environment:
      A6_PROJECTS_MGMT_CORE_PORT: 10300
      A6_PROJECTS_MGMT_CORE_MONGO_DB_URI: ${A6_INFRA_A6_MONGO_URL_LOCALHOST}
      A6_PROJECTS_MGMT_CORE_MONGO_DB_PARAMS: '?retryWrites=true&w=majority'
      A6_PROJECTS_MGMT_CORE_OAUTH_SECURITY_ISSUER_URI: http://localhost:10100

  events:
    image: "angorasix/events:${TAG-latest}"
    restart: on-failure:3
    network_mode: host
    build:
      context: ../events
    environment:
      A6_EVENTS_PORT: 10101
      A6_EVENTS_RABBITMQ_HOST: ${A6_INFRA_A6_RABBITMQ_HOST}
      A6_EVENTS_OAUTH_SECURITY_ISSUER_URI: ${A6_INFRA_A6_EVENTS_OAUTH_SECURITY_ISSUER_URI:-http://contributors:8080}

  notifications:
    image: "angorasix/notifications:${TAG-latest}"
    restart: on-failure:3
    network_mode: host
    build:
      context: ../notifications
    environment:
      A6_NOTIFICATIONS_PORT: 10102
      A6_NOTIFICATIONS_RABBITMQ_HOST: ${A6_INFRA_A6_RABBITMQ_HOST}
      A6_NOTIFICATIONS_MONGO_DB_URI: ${A6_INFRA_A6_MONGO_URL}
      A6_NOTIFICATIONS_MONGO_DB_NAME: a6Notifications
      A6_NOTIFICATIONS_MONGO_DB_PARAMS: '?retryWrites=true&w=majority'
      A6_NOTIFICATIONS_OAUTH_SECURITY_ISSUER_URI: ${A6_INFRA_A6_NOTIFICATIONS_OAUTH_SECURITY_ISSUER_URI:-http://contributors:8080}

  # FRONT
  front.aindanow:
    image: 'angorasix/front.aindanow:${TAG-latest}'
    restart: on-failure:3
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:10701/api/health']
      interval: 30s
      timeout: 30s
      retries: 1
      start_period: 0s
    network_mode: host
    build:
      context: ../front/AindaNow
      dockerfile: Dockerfile_10701
    environment:
      NEXTAUTH_URL: ${A6_INFRA_AN_CANONICAL_URL_AINDANOW}
      NEXTAUTH_URL_INTERNAL: http://localhost:10701
      AN_APP_API_SERVER_BASE_URL: ${A6_INFRA_AN_APP_API_SERVER_BASE_URL_LOCALHOST}
      AN_APP_API_BROWSER_BASE_URL: ${A6_INFRA_AN_APP_API_BROWSER_BASE_URL}
      AN_APP_AN_FRONT_PUBLIC_MEDIA_SERVER_BASE_URL: ${A6_INFRA_AN_APP_AN_FRONT_PUBLIC_MEDIA_SERVER_BASE_URL}
      AN_APP_AUTH_COOKIE: ${A6_INFRA_AN_APP_AUTH_COOKIE}
      AN_APP_THIRDPARTIES_YOUTUBE_APIKEY: ${A6_INFRA_AN_APP_THIRDPARTIES_YOUTUBE_APIKEY}
      AN_APP_OAUTH_PROVIDER_ISSUER: ${A6_INFRA_AN_APP_OAUTH_PROVIDER_ISSUER_LOCALHOST}
      AN_APP_OAUTH_PROVIDER_TOKEN_ENDPOINT: ${A6_INFRA_AN_APP_OAUTH_PROVIDER_TOKEN_ENDPOINT_LOCALHOST:-http://contributors:8080/not-overriden/token}
      AN_APP_OAUTH_PROVIDER_AUTHORIZATION_ENDPOINT: ${A6_INFRA_AN_APP_OAUTH_PROVIDER_AUTHORIZATION_ENDPOINT:-http://contributors:8080/not-overriden/authorize}
      AN_APP_OAUTH_PROVIDER_JWKS_ENDPOINT: ${A6_INFRA_AN_APP_OAUTH_PROVIDER_JWKS_ENDPOINT_LOCALHOST:-http://contributors:8080/not-overriden/oauth2/jwks}
      AN_APP_OAUTH_CLIENT_ID: ${A6_INFRA_AN_APP_OAUTH_CLIENT_ID}
      AN_APP_OAUTH_CLIENT_SECRET: ${A6_INFRA_AN_APP_OAUTH_CLIENT_SECRET}
      AN_APP_OAUTH_REDIRECT_URI: ${A6_INFRA_AN_APP_OAUTH_REDIRECT_URI}
      AN_APP_OAUTH_JWT_SECRET: ${A6_INFRA_AN_APP_OAUTH_JWT_SECRET}
      AN_APP_MAIN_SECRET: ${A6_INFRA_AN_APP_MAIN_SECRET}
      AN_FRONT_CONFIG_IMAGES_ALLOWEDDOMAINS: ${A6_INFRA_AN_FRONT_CONFIG_IMAGES_ALLOWEDDOMAINS}
      NODE_TLS_REJECT_UNAUTHORIZED: ${A6_INFRA_AN_NODE_TLS_REJECT_UNAUTHORIZED:-1}
      AN_APP_OAUTH_FW_DEBUG: ${A6_INFRA_AN_APP_OAUTH_FW_DEBUG:-true}

  

  front.angorasix:
    image: "angorasix/front.angorasix:${TAG-latest}"
    restart: unless-stopped
    networks:
      - angorasix-net
    build:
      context: ../front/AngoraSix
      dockerfile: Dockerfile_10700
    environment:
      NEXTAUTH_URL:  ${A6_INFRA_A6_CANONICAL_URL_ANGORASIX}
      NEXTAUTH_URL_INTERNAL: http://localhost:10700
      A6_APP_API_SERVER_BASE_URL: ${A6_INFRA_A6_APP_API_SERVER_BASE_URL}
      A6_APP_API_BROWSER_BASE_URL: ${A6_INFRA_A6_APP_API_BROWSER_BASE_URL}
      A6_APP_API_EVENTSOURCE_LOCALHOST: ${A6_INFRA_A6_APP_API_EVENTSOURCE_LOCALHOST}
      A6_APP_AUTH_COOKIE: ${A6_INFRA_A6_APP_AUTH_COOKIE}
      A6_APP_THIRDPARTIES_YOUTUBE_APIKEY: ${A6_INFRA_A6_APP_THIRDPARTIES_YOUTUBE_APIKEY}
      A6_APP_OAUTH_PROVIDER_ISSUER: ${A6_INFRA_A6_APP_OAUTH_PROVIDER_ISSUER}
      A6_APP_OAUTH_PROVIDER_TOKEN_ENDPOINT: ${A6_INFRA_A6_APP_OAUTH_PROVIDER_TOKEN_ENDPOINT:-http://contributors:8080/not-overriden/token}
      A6_APP_OAUTH_PROVIDER_AUTHORIZATION_ENDPOINT: ${A6_INFRA_A6_APP_OAUTH_PROVIDER_AUTHORIZATION_ENDPOINT:-http://contributors:8080/not-overriden/authorize}
      A6_APP_OAUTH_PROVIDER_JWKS_ENDPOINT: ${A6_INFRA_A6_APP_OAUTH_PROVIDER_JWKS_ENDPOINT:-http://contributors:8080/not-overriden/oauth2/jwks}
      A6_APP_OAUTH_CLIENT_ID: ${A6_INFRA_A6_APP_OAUTH_CLIENT_ID}
      A6_APP_OAUTH_CLIENT_SECRET: ${A6_INFRA_A6_APP_OAUTH_CLIENT_SECRET}
      A6_APP_OAUTH_REDIRECT_URI: ${A6_INFRA_A6_APP_OAUTH_REDIRECT_URI}
      A6_APP_OAUTH_JWT_SECRET: ${A6_INFRA_A6_APP_OAUTH_JWT_SECRET}
      A6_APP_MAIN_SECRET: ${A6_INFRA_A6_APP_MAIN_SECRET}
      NODE_TLS_REJECT_UNAUTHORIZED: ${A6_INFRA_AN_NODE_TLS_REJECT_UNAUTHORIZED:-1}
      A6_APP_OAUTH_FW_DEBUG: ${A6_INFRA_A6_APP_OAUTH_FW_DEBUG:-true}

  # GATEWAY
  gateway:
    image: 'angorasix/gateway:${TAG:-latest}'
    restart: on-failure:3
    network_mode: host
    volumes:
      - ./config/gateway:/config
    build:
      context: ../gateway
    environment:
      A6_GATEWAY_PORT: 10000
      A6_GATEWAY_CONTRIBUTORS_URI: http://localhost:10100
      A6_GATEWAY_PROJECTS_CORE_URI: http://localhost:10200
      A6_GATEWAY_PROJECTS_PRESENTATION_URI: http://localhost:10201
      A6_GATEWAY_PROJECTS_MANAGEMENT_URI: http://localhost:10300
      A6_GATEWAY_MEDIA_URI: http://localhost:10001
      A6_GATEWAY_CLUBS_URI: http://localhost:10900
      A6_GATEWAY_OAUTH_SECURITY_ISSUER_URI: http://localhost:10100
      A6_GATEWAY_CORS_ALLOWEDORIGINS: ${A6_INFRA_A6_GATEWAY_CORS_ALLOWEDORIGINS}
      A6_GATEWAY_LOGGING_LEVEL_GATEWAY: ${A6_INFRA_A6_GATEWAY_LOGGING_LEVEL:-DEBUG}
