name: Build Maven artifact and publish to maven central (via OSSRH)

on:
  workflow_call:
    secrets:
      maven-gpg-private-key:
        required: true
      ossrh-username:
        required: true
      ossrh-token:
        required: true
      maven-gpg-passphrase:
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v1
      with:
        java-version: 21
        server-id: central
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.maven-gpg-private-key }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Deploy with Maven
      run: mvn -B clean deploy -Pci-cd
      env:
        MAVEN_USERNAME: ${{ secrets.ossrh-username }}
        MAVEN_PASSWORD: ${{ secrets.ossrh-token }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.maven-gpg-passphrase }}